package com.example.aurafarm2.features.expenses

import android.content.Context
import android.net.Uri
import kotlinx.coroutines.flow.first
import java.io.BufferedReader
import java.io.InputStreamReader
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.util.UUID

data class RestoreSummary(
    val importedExpenses: Int,
    val importedIncome: Int,
    val skippedRows: Int
)

object CsvBackupManager {
    fun suggestedFileName(): String =
        "AuraFarm_Transactions_${LocalDate.now().format(DateTimeFormatter.BASIC_ISO_DATE)}.csv"

    suspend fun exportToUri(context: Context, uri: Uri) {
        val expenses = expenseEntriesFlow(context).first()
        val incomes = incomeEntriesFlow(context).first()
        val csv = buildString {
            appendLine("Date,Type,Name/Source,Category,Amount")
            expenses.forEach {
                appendCsvLine(LocalDate.ofEpochDay(it.dateEpochDay).toString(), "Expense", it.name, it.tag, it.amount.toString())
            }
            incomes.forEach {
                appendCsvLine(LocalDate.ofEpochDay(it.dateEpochDay).toString(), "Income", it.source, it.tag, it.amount.toString())
            }
        }
        context.contentResolver.openOutputStream(uri)?.use { output ->
            output.write(csv.toByteArray(Charsets.UTF_8))
        }
    }

    suspend fun restoreFromUri(context: Context, uri: Uri): RestoreSummary {
        val existingExpenses = expenseEntriesFlow(context).first().toMutableList()
        val existingIncome = incomeEntriesFlow(context).first().toMutableList()
        var importedExpenses = 0
        var importedIncome = 0
        var skipped = 0

        val lines = context.contentResolver.openInputStream(uri)?.use { input ->
            BufferedReader(InputStreamReader(input, Charsets.UTF_8)).readLines()
        }.orEmpty()

        lines.drop(1).forEach { line ->
            val columns = parseCsvLine(line)
            if (columns.size < 5) {
                skipped++
                return@forEach
            }
            runCatching {
                val date = LocalDate.parse(columns[0]).toEpochDay()
                val type = columns[1]
                val name = columns[2]
                val category = columns[3]
                val amount = columns[4].toDouble()

                if (type.equals("Expense", ignoreCase = true)) {
                    val entry = ExpenseEntry(
                        id = UUID.randomUUID().toString(),
                        dateEpochDay = date,
                        name = name,
                        tag = category,
                        amount = amount,
                        sourceApp = "CSV Import",
                        autoGenerated = false,
                        notificationHash = "",
                        createdAtEpochMillis = System.currentTimeMillis(),
                        confidenceScore = 100.0
                    )
                    if (existingExpenses.none { sameExpense(it, entry) }) {
                        saveExpenseEntry(context, entry)
                        existingExpenses.add(entry)
                        importedExpenses++
                    } else skipped++
                } else if (type.equals("Income", ignoreCase = true)) {
                    val entry = IncomeEntry(
                        id = UUID.randomUUID().toString(),
                        dateEpochDay = date,
                        source = name,
                        tag = category,
                        amount = amount,
                        sourceApp = "CSV Import",
                        autoGenerated = false,
                        notificationHash = "",
                        createdAtEpochMillis = System.currentTimeMillis(),
                        confidenceScore = 100.0
                    )
                    if (existingIncome.none { sameIncome(it, entry) }) {
                        saveIncomeEntry(context, entry)
                        existingIncome.add(entry)
                        importedIncome++
                    } else skipped++
                } else {
                    skipped++
                }
            }.onFailure {
                skipped++
            }
        }

        return RestoreSummary(importedExpenses, importedIncome, skipped)
    }

    private fun StringBuilder.appendCsvLine(vararg values: String) {
        appendLine(values.joinToString(",") { escapeCsv(it) })
    }

    private fun escapeCsv(value: String): String {
        val escaped = value.replace("\"", "\"\"")
        return if (escaped.any { it == ',' || it == '"' || it == '\n' }) "\"$escaped\"" else escaped
    }

    private fun parseCsvLine(line: String): List<String> {
        val result = mutableListOf<String>()
        val current = StringBuilder()
        var inQuotes = false
        var i = 0
        while (i < line.length) {
            val char = line[i]
            when {
                char == '"' && inQuotes && i + 1 < line.length && line[i + 1] == '"' -> {
                    current.append('"')
                    i++
                }
                char == '"' -> inQuotes = !inQuotes
                char == ',' && !inQuotes -> {
                    result.add(current.toString())
                    current.clear()
                }
                else -> current.append(char)
            }
            i++
        }
        result.add(current.toString())
        return result
    }

    private fun sameExpense(a: ExpenseEntry, b: ExpenseEntry): Boolean =
        a.amount == b.amount && a.dateEpochDay == b.dateEpochDay && a.name.equals(b.name, ignoreCase = true)

    private fun sameIncome(a: IncomeEntry, b: IncomeEntry): Boolean =
        a.amount == b.amount && a.dateEpochDay == b.dateEpochDay && a.source.equals(b.source, ignoreCase = true)
}
