package com.example.aurafarm2.features.expenses

import android.content.Context
import android.net.Uri
import kotlinx.coroutines.flow.first
import java.io.BufferedReader
import java.io.InputStreamReader
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.util.UUID

data class RestoreSummary(
    val importedExpenses: Int,
    val importedIncome: Int,
    val importedBudgets: Int,
    val importedRecurring: Int,
    val importedCorrections: Int,
    val skippedRows: Int
)

object CsvBackupManager {
    fun suggestedFileName(): String =
        "AuraFarm_Backup_${LocalDate.now().format(DateTimeFormatter.BASIC_ISO_DATE)}.csv"

    suspend fun exportToUri(context: Context, uri: Uri) {
        val expenses = expenseEntriesFlow(context).first()
        val incomes = incomeEntriesFlow(context).first()
        val budgets = budgetsFlow(context).first()
        val recurring = recurringEntriesFlow(context).first()
        val corrections = categoryCorrectionsFlow(context).first()
        val pendings = pendingTransactionsFlow(context).first()
        val csv = buildString {
            appendLine("section,id,date,name,category,amount,sourceApp,autoGenerated,notificationHash,createdAtEpochMillis,extra1,extra2")
            expenses.forEach {
                appendCsvLine("expense", it.id, LocalDate.ofEpochDay(it.dateEpochDay).toString(), it.name, it.tag, it.amount.toString(), it.sourceApp, it.autoGenerated.toString(), it.notificationHash, it.createdAtEpochMillis.toString(), it.confidenceScore.toString(), "")
            }
            incomes.forEach {
                appendCsvLine("income", it.id, LocalDate.ofEpochDay(it.dateEpochDay).toString(), it.source, it.tag, it.amount.toString(), it.sourceApp, it.autoGenerated.toString(), it.notificationHash, it.createdAtEpochMillis.toString(), it.confidenceScore.toString(), "")
            }
            budgets.forEach {
                appendCsvLine("budget", it.id, "", it.category, "", it.limit.toString(), "", "", "", "", "", "")
            }
            recurring.forEach {
                appendCsvLine("recurring", it.id, LocalDate.ofEpochDay(it.nextDueEpochDay).toString(), it.name, it.category, it.amount.toString(), "", it.enabled.toString(), "", "", it.kind, it.repeat)
            }
            corrections.forEach {
                appendCsvLine("correction", "", "", it.merchant, it.category, "", "", "", "", "", it.selectionCount.toString(), "")
            }
            pendings.forEach {
                appendCsvLine("pending", it.id, LocalDate.ofEpochDay(it.dateEpochDay).toString(), it.merchant, it.suggestedCategory, it.amount.toString(), it.sourceApp, "true", it.notificationHash, it.createdAtEpochMillis.toString(), it.type, it.confidenceScore.toString())
            }
        }
        context.contentResolver.openOutputStream(uri)?.use { output ->
            output.write(csv.toByteArray(Charsets.UTF_8))
        }
    }

    suspend fun restoreFromUri(context: Context, uri: Uri): RestoreSummary {
        val existingExpenses = expenseEntriesFlow(context).first().toMutableList()
        val existingIncome = incomeEntriesFlow(context).first().toMutableList()
        val existingBudgets = budgetsFlow(context).first().toMutableList()
        val existingRecurring = recurringEntriesFlow(context).first().toMutableList()
        val existingCorrections = categoryCorrectionsFlow(context).first().toMutableList()
        val existingPendings = pendingTransactionsFlow(context).first().toMutableList()
        var importedExpenses = 0
        var importedIncome = 0
        var importedBudgets = 0
        var importedRecurring = 0
        var importedCorrections = 0
        var importedPendings = 0
        var skipped = 0

        val lines = context.contentResolver.openInputStream(uri)?.use { input ->
            BufferedReader(InputStreamReader(input, Charsets.UTF_8)).readLines()
        }.orEmpty()

        lines.drop(1).forEach { line ->
            val columns = parseCsvLine(line)
            if (columns.size < 12) {
                skipped++
                return@forEach
            }
            runCatching {
                when (columns[0]) {
                    "expense" -> {
                        val entry = ExpenseEntry(
                            id = columns[1].ifBlank { UUID.randomUUID().toString() },
                            dateEpochDay = LocalDate.parse(columns[2]).toEpochDay(),
                            name = columns[3],
                            tag = columns[4],
                            amount = columns[5].toDouble(),
                            sourceApp = columns[6],
                            autoGenerated = columns[7].toBoolean(),
                            notificationHash = columns[8],
                            createdAtEpochMillis = columns[9].toLongOrNull() ?: 0L,
                            confidenceScore = columns.getOrNull(10)?.toDoubleOrNull() ?: 100.0
                        )
                        if (existingExpenses.none { it.id == entry.id || sameExpense(it, entry) }) {
                            saveExpenseEntry(context, entry)
                            existingExpenses.add(entry)
                            importedExpenses++
                        } else skipped++
                    }
                    "income" -> {
                        val entry = IncomeEntry(
                            id = columns[1].ifBlank { UUID.randomUUID().toString() },
                            dateEpochDay = LocalDate.parse(columns[2]).toEpochDay(),
                            source = columns[3],
                            tag = columns[4],
                            amount = columns[5].toDouble(),
                            sourceApp = columns[6],
                            autoGenerated = columns[7].toBoolean(),
                            notificationHash = columns[8],
                            createdAtEpochMillis = columns[9].toLongOrNull() ?: 0L,
                            confidenceScore = columns.getOrNull(10)?.toDoubleOrNull() ?: 100.0
                        )
                        if (existingIncome.none { it.id == entry.id || sameIncome(it, entry) }) {
                            saveIncomeEntry(context, entry)
                            existingIncome.add(entry)
                            importedIncome++
                        } else skipped++
                    }
                    "budget" -> {
                        val budget = Budget(columns[1].ifBlank { UUID.randomUUID().toString() }, columns[3], columns[5].toDouble())
                        if (existingBudgets.none { it.category == budget.category }) {
                            saveBudget(context, budget)
                            existingBudgets.add(budget)
                            importedBudgets++
                        } else skipped++
                    }
                    "recurring" -> {
                        val entry = RecurringEntry(
                            id = columns[1].ifBlank { UUID.randomUUID().toString() },
                            nextDueEpochDay = LocalDate.parse(columns[2]).toEpochDay(),
                            name = columns[3],
                            category = columns[4],
                            amount = columns[5].toDouble(),
                            enabled = columns[7].toBoolean(),
                            kind = columns[10].ifBlank { "Expense" },
                            repeat = columns[11].ifBlank { "Monthly" }
                        )
                        if (existingRecurring.none { it.id == entry.id }) {
                            saveRecurringEntry(context, entry)
                            existingRecurring.add(entry)
                            importedRecurring++
                        } else skipped++
                    }
                    "correction" -> {
                        val correction = CategoryCorrection(columns[3], columns[4], columns.getOrNull(10)?.toIntOrNull() ?: 1)
                        if (existingCorrections.none { it.merchant.equals(correction.merchant, true) && it.category.equals(correction.category, true) }) {
                            saveCategoryCorrection(context, correction)
                            existingCorrections.add(correction)
                            importedCorrections++
                        } else skipped++
                    }
                    "pending" -> {
                        val pending = PendingTransaction(
                            id = columns[1].ifBlank { UUID.randomUUID().toString() },
                            dateEpochDay = LocalDate.parse(columns[2]).toEpochDay(),
                            merchant = columns[3],
                            suggestedCategory = columns[4],
                            amount = columns[5].toDouble(),
                            sourceApp = columns[6],
                            notificationHash = columns[8],
                            createdAtEpochMillis = columns[9].toLongOrNull() ?: 0L,
                            type = columns.getOrNull(10) ?: "Expense",
                            confidenceScore = columns.getOrNull(11)?.toDoubleOrNull() ?: 50.0
                        )
                        if (existingPendings.none { it.id == pending.id }) {
                            savePendingTransaction(context, pending)
                            existingPendings.add(pending)
                            importedPendings++
                        } else skipped++
                    }
                    else -> skipped++
                }
            }.onFailure {
                skipped++
            }
        }

        return RestoreSummary(importedExpenses, importedIncome, importedBudgets, importedRecurring, importedCorrections, skipped)
    }

    private fun StringBuilder.appendCsvLine(vararg values: String) {
        appendLine(values.joinToString(",") { escapeCsv(it) })
    }

    private fun escapeCsv(value: String): String {
        val escaped = value.replace("\"", "\"\"")
        return if (escaped.any { it == ',' || it == '"' || it == '\n' }) "\"$escaped\"" else escaped
    }

    private fun parseCsvLine(line: String): List<String> {
        val result = mutableListOf<String>()
        val current = StringBuilder()
        var inQuotes = false
        var i = 0
        while (i < line.length) {
            val char = line[i]
            when {
                char == '"' && inQuotes && i + 1 < line.length && line[i + 1] == '"' -> {
                    current.append('"')
                    i++
                }
                char == '"' -> inQuotes = !inQuotes
                char == ',' && !inQuotes -> {
                    result.add(current.toString())
                    current.clear()
                }
                else -> current.append(char)
            }
            i++
        }
        result.add(current.toString())
        return result
    }

    private fun sameExpense(a: ExpenseEntry, b: ExpenseEntry): Boolean =
        a.amount == b.amount && a.dateEpochDay == b.dateEpochDay && a.name.equals(b.name, true)

    private fun sameIncome(a: IncomeEntry, b: IncomeEntry): Boolean =
        a.amount == b.amount && a.dateEpochDay == b.dateEpochDay && a.source.equals(b.source, true)
}
