package com.example.aurafarm2.features.expenses

import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import androidx.core.app.NotificationCompat
import com.example.aurafarm2.MainActivity
import com.example.aurafarm2.REMINDER_CHANNEL_ID
import kotlinx.coroutines.flow.first
import java.security.MessageDigest
import java.time.Instant
import java.time.LocalDate
import java.time.ZoneId
import java.util.Locale
import java.util.UUID
import kotlin.math.max

enum class NotificationSourceType(val priority: Int) {
    UPI(4),
    BANK(3),
    SMS(2),
    EMAIL(1),
    UNKNOWN(0)
}

fun extractSourceType(sourceApp: String): NotificationSourceType {
    val pkg = sourceApp.lowercase(Locale.ENGLISH)
    return when {
        "com.google.android.apps.nbu.paisa.user" in pkg || "com.phonepe.app" in pkg || "net.one97.paytm" in pkg || "in.org.npci.upiapp" in pkg || "com.pop.upi" in pkg -> NotificationSourceType.UPI
        "sbi" in pkg || "hdfc" in pkg || "icici" in pkg || "axis" in pkg || "kotak" in pkg || "bob" in pkg || "bank" in pkg -> NotificationSourceType.BANK
        "mms" in pkg || "sms" in pkg || "messaging" in pkg -> NotificationSourceType.SMS
        "gmail" in pkg || "email" in pkg -> NotificationSourceType.EMAIL
        else -> NotificationSourceType.UNKNOWN
    }
}

data class DetectedTransaction(
    val amount: Double,
    val type: String,
    val merchant: String,
    val epochMillis: Long,
    val sourceApp: String,
    val notificationHash: String
)

object NotificationTransactionProcessor {
    suspend fun process(context: Context, sourceApp: String, title: String, text: String, postedAt: Long): Boolean {
        val settings = appSettingsFlow(context).first()
        if (!settings.smartDetectionEnabled) return false

        val fullText = listOf(title, text).filter { it.isNotBlank() }.joinToString(" ")
        val detected = TransactionExtractor.extract(fullText, sourceApp, postedAt) ?: return false
        
        val expenses = expenseEntriesFlow(context).first()
        val incomes = incomeEntriesFlow(context).first()
        val pendings = pendingTransactionsFlow(context).first()
        
        if (isDuplicate(detected, expenses, incomes, pendings)) return false

        val corrections = categoryCorrectionsFlow(context).first()
        val prediction = TransactionCategorizer.categorize(detected.merchant, corrections)
        
        val epochDay = Instant.ofEpochMilli(detected.epochMillis)
            .atZone(ZoneId.systemDefault())
            .toLocalDate()
            .toEpochDay()

        val id = UUID.randomUUID().toString()

        if (prediction.confidence < 60.0) {
            savePendingTransaction(context, PendingTransaction(
                id = id,
                amount = detected.amount,
                merchant = detected.merchant,
                type = detected.type,
                dateEpochDay = epochDay,
                sourceApp = detected.sourceApp,
                notificationHash = detected.notificationHash,
                createdAtEpochMillis = System.currentTimeMillis(),
                suggestedCategory = prediction.category,
                confidenceScore = prediction.confidence
            ))
            sendNotification(context, "Aura Farm Review Queue", "Low confidence transaction detected. Tap to review.")
            return true
        }

        val tag = if (prediction.category == "Uncategorized" && detected.type == "Income") "Other" else prediction.category

        if (detected.type == "Income") {
            saveIncomeEntry(context, IncomeEntry(
                id = id, source = detected.merchant, tag = tag, amount = detected.amount,
                dateEpochDay = epochDay, sourceApp = detected.sourceApp, autoGenerated = true,
                notificationHash = detected.notificationHash, createdAtEpochMillis = System.currentTimeMillis(),
                confidenceScore = prediction.confidence
            ))
        } else {
            val amount = detected.amount
            saveExpenseEntry(context, ExpenseEntry(
                id = id, name = detected.merchant, tag = tag, amount = amount,
                dateEpochDay = epochDay, sourceApp = detected.sourceApp, autoGenerated = true,
                notificationHash = detected.notificationHash, createdAtEpochMillis = System.currentTimeMillis(),
                confidenceScore = prediction.confidence
            ))
            checkBudget(context, tag)
        }

        if (prediction.confidence in 60.0..90.0) {
            sendNotification(context, "Transaction Auto-Saved", "Categorized as $tag. Tap to verify.")
        }

        return true
    }

    private suspend fun checkBudget(context: Context, category: String) {
        val budgets = budgetsFlow(context).first()
        val budget = budgets.find { it.category.equals(category, ignoreCase = true) } ?: return
        
        val startOfMonth = LocalDate.now().withDayOfMonth(1).toEpochDay()
        val expenses = expenseEntriesFlow(context).first().filter { 
            it.tag.equals(category, ignoreCase = true) && it.dateEpochDay >= startOfMonth
        }
        val spent = expenses.sumOf { it.amount }
        
        if (spent > budget.limit) {
            sendNotification(
                context, 
                "Budget Exceeded", 
                "You have exceeded your $category budget. Spent: ${String.format("%.2f", spent)} / ${String.format("%.2f", budget.limit)}"
            )
        }
    }

    private fun sendNotification(context: Context, title: String, text: String) {
        val intent = Intent(context, MainActivity::class.java).apply {
            flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK
        }
        val pendingIntent = PendingIntent.getActivity(
            context, 0, intent,
            PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE
        )
        val builder = NotificationCompat.Builder(context, REMINDER_CHANNEL_ID)
            .setSmallIcon(android.R.drawable.ic_dialog_info)
            .setContentTitle(title)
            .setContentText(text)
            .setPriority(NotificationCompat.PRIORITY_DEFAULT)
            .setContentIntent(pendingIntent)
            .setAutoCancel(true)

        val manager = context.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
        manager.notify((System.currentTimeMillis() % 10000).toInt(), builder.build())
    }

    private fun isDuplicate(
        detected: DetectedTransaction,
        expenses: List<ExpenseEntry>,
        incomes: List<IncomeEntry>,
        pendings: List<PendingTransaction>
    ): Boolean {
        val windowMillis = 2 * 60 * 1000L
        
        // Match exact hash or just same amount within window
        val expDup = expenses.any {
            it.notificationHash.isNotBlank() && it.notificationHash == detected.notificationHash ||
                (kotlin.math.abs((it.createdAtEpochMillis.takeIf { v -> v > 0 } ?: detected.epochMillis) - detected.epochMillis) <= windowMillis &&
                    it.amount == detected.amount && detected.type == "Expense")
        }
        val incDup = incomes.any {
            it.notificationHash.isNotBlank() && it.notificationHash == detected.notificationHash ||
                (kotlin.math.abs((it.createdAtEpochMillis.takeIf { v -> v > 0 } ?: detected.epochMillis) - detected.epochMillis) <= windowMillis &&
                    it.amount == detected.amount && detected.type == "Income")
        }
        val penDup = pendings.any {
            it.notificationHash.isNotBlank() && it.notificationHash == detected.notificationHash ||
                (kotlin.math.abs((it.createdAtEpochMillis.takeIf { v -> v > 0 } ?: detected.epochMillis) - detected.epochMillis) <= windowMillis &&
                    it.amount == detected.amount && it.type == detected.type)
        }
        return expDup || incDup || penDup
    }
}

object TransactionExtractor {
    private val amountRegex = Regex("""(?i)(?:₹|rs\.?|inr)\s*([0-9][0-9,]*(?:\.[0-9]{1,2})?)|([0-9][0-9,]*(?:\.[0-9]{1,2})?)\s*(?:rs|inr)""")
    private val incomeWords = listOf("credited", "credit", "received", "refund", "cashback received", "deposited", "salary")
    private val expenseWords = listOf("debited", "debit", "paid", "sent", "spent", "purchase", "withdrawn", "payment")
    private val blockedWords = listOf("otp", "one time password", "offer", "sale", "discount", "promo", "reward", "win", "cashback today", "coupon")

    fun extract(text: String, sourceApp: String, postedAt: Long): DetectedTransaction? {
        val normalized = text.lowercase(Locale.ENGLISH)
        if (blockedWords.any { normalized.contains(it) }) return null
        val amount = amountRegex.find(text)?.let { match ->
            (match.groupValues[1].ifBlank { match.groupValues[2] }).replace(",", "").toDoubleOrNull()
        } ?: return null

        val type = when {
            incomeWords.any { normalized.contains(it) } -> "Income"
            expenseWords.any { normalized.contains(it) } -> "Expense"
            else -> return null
        }
        val merchant = extractMerchant(text, type).ifBlank {
            if (type == "Income") "Income" else sourceApp.substringAfterLast('.')
        }
        return DetectedTransaction(
            amount = amount,
            type = type,
            merchant = merchant,
            epochMillis = postedAt.takeIf { it > 0 } ?: System.currentTimeMillis(),
            sourceApp = sourceApp,
            notificationHash = sha256("$sourceApp|$postedAt|$text")
        )
    }

    private fun extractMerchant(text: String, type: String): String {
        val patterns = if (type == "Income") {
            listOf(
                Regex("""(?i)(salary|refund|cashback|deposit|received from)\s+([A-Za-z0-9 .&'-]{2,40})"""),
                Regex("""(?i)from\s+([A-Za-z0-9 .&'-]{2,40})""")
            )
        } else {
            listOf(
                Regex("""(?i)(?:paid to|sent to|to|at|for)\s+([A-Za-z0-9 .&'-]{2,40})"""),
                Regex("""(?i)([A-Za-z0-9 .&'-]{2,40})\s+(?:using upi|via upi)""")
            )
        }
        return patterns.firstNotNullOfOrNull { regex ->
            regex.find(text)?.groupValues?.lastOrNull()?.cleanMerchant()
        }.orEmpty()
    }

    private fun String.cleanMerchant(): String =
        replace(Regex("""(?i)\b(using|via|upi|account|a/c|ending|on|at)\b.*$"""), "")
            .trim(' ', '.', ',', '-', ':')
            .ifBlank { "Unknown" }

    private fun sha256(value: String): String {
        val digest = MessageDigest.getInstance("SHA-256").digest(value.toByteArray())
        return digest.joinToString("") { "%02x".format(it) }
    }
}

object TransactionCategorizer {
    private val rules = mapOf(
        "Food" to listOf("swiggy", "zomato", "domino", "mcdonald", "restaurant", "cafe", "food"),
        "Transport" to listOf("uber", "ola", "rapido", "metro", "fuel", "petrol", "diesel"),
        "Shopping" to listOf("amazon", "flipkart", "myntra", "ajio", "shop"),
        "Utilities" to listOf("airtel", "jio", "tata power", "electricity", "water", "gas", "bill"),
        "Entertainment" to listOf("netflix", "spotify", "prime video", "hotstar", "bookmyshow"),
        "Health" to listOf("apollo", "practo", "pharmeasy", "pharmacy", "hospital", "clinic"),
        "Other" to listOf("udemy", "coursera", "unacademy", "school", "college", "education")
    )

    fun categorize(merchant: String, corrections: List<CategoryCorrection>): CategoryPrediction {
        val normalized = merchant.lowercase(Locale.ENGLISH)
        
        val correction = corrections.maxByOrNull { 
            if (normalized.contains(it.merchant.lowercase(Locale.ENGLISH))) it.selectionCount else -1 
        }
        if (correction != null && correction.selectionCount > 0) {
            val confidence = if (correction.selectionCount >= 3) 95.0 else 90.0
            return CategoryPrediction(correction.category, confidence)
        }
        
        rules.entries.firstOrNull { (_, keywords) -> keywords.any { normalized.contains(it) } }?.let {
            return CategoryPrediction(it.key, 85.0)
        }
        
        val fallback = BasicMerchantClassifier.predict(normalized, corrections)
        val conf = fallback.confidence * 100.0
        return CategoryPrediction(
            category = if (conf >= 45.0) fallback.category else "Uncategorized",
            confidence = conf
        )
    }
}

data class CategoryPrediction(val category: String, val confidence: Double)

object BasicMerchantClassifier {
    private val seeds = listOf(
        "biryani cafe" to "Food",
        "pizza outlet" to "Food",
        "cab ride" to "Transport",
        "fuel station" to "Transport",
        "online store" to "Shopping",
        "mobile recharge" to "Utilities",
        "movie ticket" to "Entertainment",
        "medical store" to "Health",
        "online course" to "Other"
    )

    fun predict(merchant: String, corrections: List<CategoryCorrection>): CategoryPrediction {
        val examples = seeds + corrections.map { it.merchant to it.category }
        val best = examples.map { (sample, category) ->
            category to similarity(merchant, sample.lowercase(Locale.ENGLISH))
        }.maxByOrNull { it.second } ?: return CategoryPrediction("Uncategorized", 0.0)
        return CategoryPrediction(best.first, best.second)
    }

    private fun similarity(a: String, b: String): Double {
        val aTokens = a.split(Regex("""\W+""")).filter { it.isNotBlank() }.toSet()
        val bTokens = b.split(Regex("""\W+""")).filter { it.isNotBlank() }.toSet()
        if (aTokens.isEmpty() || bTokens.isEmpty()) return 0.0
        val overlap = aTokens.intersect(bTokens).size.toDouble()
        return overlap / max(aTokens.size, bTokens.size)
    }
}
