package com.example.aurafarm2.features.expenses

import android.content.Context
import kotlinx.coroutines.flow.first
import java.security.MessageDigest
import java.time.Instant
import java.time.ZoneId
import java.util.Locale
import java.util.UUID
import kotlin.math.max

data class DetectedTransaction(
    val amount: Double,
    val type: String,
    val merchant: String,
    val epochMillis: Long,
    val sourceApp: String,
    val notificationHash: String
)

object NotificationTransactionProcessor {
    suspend fun process(context: Context, sourceApp: String, title: String, text: String, postedAt: Long): Boolean {
        val settings = appSettingsFlow(context).first()
        if (!settings.smartDetectionEnabled) return false

        val fullText = listOf(title, text).filter { it.isNotBlank() }.joinToString(" ")
        val detected = TransactionExtractor.extract(fullText, sourceApp, postedAt) ?: return false
        val expenses = expenseEntriesFlow(context).first()
        val incomes = incomeEntriesFlow(context).first()
        if (isDuplicate(detected, expenses, incomes)) return false

        val corrections = categoryCorrectionsFlow(context).first()
        val category = TransactionCategorizer.categorize(detected.merchant, corrections)
        val epochDay = Instant.ofEpochMilli(detected.epochMillis)
            .atZone(ZoneId.systemDefault())
            .toLocalDate()
            .toEpochDay()

        if (detected.type == "Income") {
            saveIncomeEntry(
                context,
                IncomeEntry(
                    id = UUID.randomUUID().toString(),
                    source = detected.merchant,
                    tag = if (category == "Uncategorized") "Other" else category,
                    amount = detected.amount,
                    dateEpochDay = epochDay,
                    sourceApp = detected.sourceApp,
                    autoGenerated = true,
                    notificationHash = detected.notificationHash,
                    createdAtEpochMillis = System.currentTimeMillis()
                )
            )
        } else {
            saveExpenseEntry(
                context,
                ExpenseEntry(
                    id = UUID.randomUUID().toString(),
                    name = detected.merchant,
                    tag = category,
                    amount = detected.amount,
                    dateEpochDay = epochDay,
                    sourceApp = detected.sourceApp,
                    autoGenerated = true,
                    notificationHash = detected.notificationHash,
                    createdAtEpochMillis = System.currentTimeMillis()
                )
            )
        }
        return true
    }

    private fun isDuplicate(
        detected: DetectedTransaction,
        expenses: List<ExpenseEntry>,
        incomes: List<IncomeEntry>
    ): Boolean {
        val windowMillis = 2 * 60 * 1000L
        val expenseDuplicate = expenses.any {
            it.notificationHash.isNotBlank() && it.notificationHash == detected.notificationHash ||
                (kotlin.math.abs((it.createdAtEpochMillis.takeIf { value -> value > 0 } ?: detected.epochMillis) - detected.epochMillis) <= windowMillis &&
                    it.amount == detected.amount &&
                    it.name.equals(detected.merchant, ignoreCase = true))
        }
        val incomeDuplicate = incomes.any {
            it.notificationHash.isNotBlank() && it.notificationHash == detected.notificationHash ||
                (kotlin.math.abs((it.createdAtEpochMillis.takeIf { value -> value > 0 } ?: detected.epochMillis) - detected.epochMillis) <= windowMillis &&
                    it.amount == detected.amount &&
                    it.source.equals(detected.merchant, ignoreCase = true))
        }
        return expenseDuplicate || incomeDuplicate
    }
}

object TransactionExtractor {
    private val amountRegex = Regex("""(?i)(?:₹|rs\.?|inr)\s*([0-9][0-9,]*(?:\.[0-9]{1,2})?)|([0-9][0-9,]*(?:\.[0-9]{1,2})?)\s*(?:rs|inr)""")
    private val incomeWords = listOf("credited", "credit", "received", "refund", "cashback received", "deposited", "salary")
    private val expenseWords = listOf("debited", "debit", "paid", "sent", "spent", "purchase", "withdrawn", "payment")
    private val blockedWords = listOf("otp", "one time password", "offer", "sale", "discount", "promo", "reward", "win", "cashback today", "coupon")

    fun extract(text: String, sourceApp: String, postedAt: Long): DetectedTransaction? {
        val normalized = text.lowercase(Locale.ENGLISH)
        if (blockedWords.any { normalized.contains(it) }) return null
        val amount = amountRegex.find(text)?.let { match ->
            (match.groupValues[1].ifBlank { match.groupValues[2] }).replace(",", "").toDoubleOrNull()
        } ?: return null

        val type = when {
            incomeWords.any { normalized.contains(it) } -> "Income"
            expenseWords.any { normalized.contains(it) } -> "Expense"
            else -> return null
        }
        val merchant = extractMerchant(text, type).ifBlank {
            if (type == "Income") "Income" else sourceApp.substringAfterLast('.')
        }
        return DetectedTransaction(
            amount = amount,
            type = type,
            merchant = merchant,
            epochMillis = postedAt.takeIf { it > 0 } ?: System.currentTimeMillis(),
            sourceApp = sourceApp,
            notificationHash = sha256("$sourceApp|$postedAt|$text")
        )
    }

    private fun extractMerchant(text: String, type: String): String {
        val patterns = if (type == "Income") {
            listOf(
                Regex("""(?i)(salary|refund|cashback|deposit|received from)\s+([A-Za-z0-9 .&'-]{2,40})"""),
                Regex("""(?i)from\s+([A-Za-z0-9 .&'-]{2,40})""")
            )
        } else {
            listOf(
                Regex("""(?i)(?:paid to|sent to|to|at|for)\s+([A-Za-z0-9 .&'-]{2,40})"""),
                Regex("""(?i)([A-Za-z0-9 .&'-]{2,40})\s+(?:using upi|via upi)""")
            )
        }
        return patterns.firstNotNullOfOrNull { regex ->
            regex.find(text)?.groupValues?.lastOrNull()?.cleanMerchant()
        }.orEmpty()
    }

    private fun String.cleanMerchant(): String =
        replace(Regex("""(?i)\b(using|via|upi|account|a/c|ending|on|at)\b.*$"""), "")
            .trim(' ', '.', ',', '-', ':')
            .ifBlank { "Unknown" }

    private fun sha256(value: String): String {
        val digest = MessageDigest.getInstance("SHA-256").digest(value.toByteArray())
        return digest.joinToString("") { "%02x".format(it) }
    }
}

object TransactionCategorizer {
    private val rules = mapOf(
        "Food" to listOf("swiggy", "zomato", "domino", "mcdonald", "restaurant", "cafe", "food"),
        "Transport" to listOf("uber", "ola", "rapido", "metro", "fuel", "petrol", "diesel"),
        "Shopping" to listOf("amazon", "flipkart", "myntra", "ajio", "shop"),
        "Utilities" to listOf("airtel", "jio", "tata power", "electricity", "water", "gas", "bill"),
        "Entertainment" to listOf("netflix", "spotify", "prime video", "hotstar", "bookmyshow"),
        "Health" to listOf("apollo", "practo", "pharmeasy", "pharmacy", "hospital", "clinic"),
        "Other" to listOf("udemy", "coursera", "unacademy", "school", "college", "education")
    )

    fun categorize(merchant: String, corrections: List<CategoryCorrection>): String {
        val normalized = merchant.lowercase(Locale.ENGLISH)
        corrections.firstOrNull { normalized.contains(it.merchant.lowercase(Locale.ENGLISH)) }?.let {
            return it.category
        }
        rules.entries.firstOrNull { (_, keywords) -> keywords.any { normalized.contains(it) } }?.let {
            return it.key
        }
        return BasicMerchantClassifier.predict(normalized, corrections).takeIf { it.confidence >= 0.45 }?.category
            ?: "Uncategorized"
    }
}

data class CategoryPrediction(val category: String, val confidence: Double)

object BasicMerchantClassifier {
    private val seeds = listOf(
        "biryani cafe" to "Food",
        "pizza outlet" to "Food",
        "cab ride" to "Transport",
        "fuel station" to "Transport",
        "online store" to "Shopping",
        "mobile recharge" to "Utilities",
        "movie ticket" to "Entertainment",
        "medical store" to "Health",
        "online course" to "Other"
    )

    fun predict(merchant: String, corrections: List<CategoryCorrection>): CategoryPrediction {
        val examples = seeds + corrections.map { it.merchant to it.category }
        val best = examples.map { (sample, category) ->
            category to similarity(merchant, sample.lowercase(Locale.ENGLISH))
        }.maxByOrNull { it.second } ?: return CategoryPrediction("Uncategorized", 0.0)
        return CategoryPrediction(best.first, best.second)
    }

    private fun similarity(a: String, b: String): Double {
        val aTokens = a.split(Regex("""\W+""")).filter { it.isNotBlank() }.toSet()
        val bTokens = b.split(Regex("""\W+""")).filter { it.isNotBlank() }.toSet()
        if (aTokens.isEmpty() || bTokens.isEmpty()) return 0.0
        val overlap = aTokens.intersect(bTokens).size.toDouble()
        return overlap / max(aTokens.size, bTokens.size)
    }
}
